spring.application.name=afyacheck
spring.datasource.url=jdbc:postgresql://localhost:5432/AfyaCheck
spring.datasource.username=postgres
spring.datasource.password=REDACTED_ROTATE_ME
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## Spring Security default user (optional for quick test)
#spring.security.user.name=admin
#spring.security.user.password=admin

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.afyacheck@gmail.com
spring.mail.password=ROTATED_MAIL_PASSWORD_REMOVED  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=noreply.afyacheck@gmail.com

# Enable Spring Security debug logs
logging.level.org.springframework.security=DEBUG
