-- Baseline schema, generated from the JPA entities as they existed on this
-- branch (via Hibernate ddl-auto=create against a scratch database, then
-- pg_dump --schema-only). Represents the schema Hibernate was already
-- creating in every environment before Flyway was introduced.

CREATE TABLE answer (
    created_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    session_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    answer_value text,
    question_key character varying(255) NOT NULL,
    CONSTRAINT answer_pkey PRIMARY KEY (id)
);

CREATE TABLE password_reset_tokens (
    expiry_date timestamp(6) without time zone,
    user_id bigint,
    id character varying(255) NOT NULL,
    token character varying(255),
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT password_reset_tokens_user_id_key UNIQUE (user_id)
);

CREATE TABLE question (
    display_order integer,
    is_active boolean,
    max_value integer,
    min_value integer,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    description text,
    question_key character varying(255) NOT NULL,
    question_text text NOT NULL,
    question_type character varying(255) NOT NULL,
    section_title character varying(255),
    options jsonb,
    CONSTRAINT question_pkey PRIMARY KEY (id),
    CONSTRAINT question_question_key_key UNIQUE (question_key)
);

CREATE TABLE questionnaire (
    completed_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    risk_level character varying(255),
    CONSTRAINT questionnaire_pkey PRIMARY KEY (id)
);

CREATE TABLE risk_assessment (
    risk_score integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    session_id bigint NOT NULL,
    risk_level character varying(255) NOT NULL,
    recommendations jsonb,
    CONSTRAINT risk_assessment_pkey PRIMARY KEY (id)
);

CREATE TABLE session (
    risk_score integer,
    created_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp(6) without time zone,
    status character varying(50),
    session_id text NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (id),
    CONSTRAINT session_session_id_key UNIQUE (session_id)
);

CREATE TABLE users (
    email_verified boolean NOT NULL,
    enabled boolean,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    reset_token_expiry timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255),
    reset_token character varying(255),
    role character varying(255) NOT NULL,
    username character varying(255),
    verification_token character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying, 'GITHUB'::character varying, 'APPLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE verification_token (
    expiry_date timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    token character varying(255),
    CONSTRAINT verification_token_pkey PRIMARY KEY (id),
    CONSTRAINT verification_token_user_id_key UNIQUE (user_id)
);

ALTER TABLE ONLY verification_token
    ADD CONSTRAINT fk3asw9wnv76uxu3kr1ekq4i1ld FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY questionnaire
    ADD CONSTRAINT fkemxxmaqakd9stj0adwl3h1sot FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY answer
    ADD CONSTRAINT fkn2jma4u3akg79lhs9t7b24lvo FOREIGN KEY (session_id) REFERENCES session(id);

ALTER TABLE ONLY risk_assessment
    ADD CONSTRAINT fkpbjg69oag2x8v79yqv4j3n74 FOREIGN KEY (session_id) REFERENCES session(id);
