-- The "questionnaire" table has no active repository (QuestionnaireRepository was fully
-- commented out) -- session + risk_assessment already record every completed assessment and
-- its risk level, so nothing in the app reads or writes this table.
DROP TABLE IF EXISTS questionnaire;

-- Admin actions (enabling/disabling users, editing the question bank) currently leave no
-- trail, which is a real gap for a health-data application whose admin console can mutate
-- user access and the question bank. Records who did what, to what, and when.
CREATE TABLE admin_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    actor_email character varying(255) NOT NULL,
    action character varying(100) NOT NULL,
    target_type character varying(100),
    target_id character varying(100),
    details text,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_admin_audit_log_created_at ON admin_audit_log (created_at);
