-- Curated health centers, admin-managed (see AdminController health-center CRUD). The
-- health-centers page still falls back to a live Google Places search when no curated centers
-- are near the user, so this starts empty rather than needing to be seeded.
CREATE TABLE health_center (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    address text,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    phone character varying(50),
    hours character varying(255),
    services jsonb,
    sti_testing_available boolean,
    is_active boolean,
    CONSTRAINT health_center_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_health_center_is_active ON health_center (is_active);
